### ISSUE TITLE
有些页面解析下一页报错了

### ISSUE THREAD

**Issue by tianshaokai** [boildcoffee/welfare#1]
W/System.err:     at java.lang.Integer.parseInt(Integer.java:367)
05-16 10:58:20.000 14885-14885/com.boiledcoffee.welfare W/System.err:     at java.lang.Integer.parseInt(Integer.java:334)
05-16 10:58:20.000 14885-14885/com.boiledcoffee.welfare W/System.err:     at com.boiledcoffee.welfare.repository.ImageRepository.hasPage(ImageRepository.java:212)
05-16 10:58:20.000 14885-14885/com.boiledcoffee.welfare W/System.err:     at com.boiledcoffee.welfare.repository.ImageRepository.parseAtlasData(ImageRepository.java:168)
05-16 10:58:20.000 14885-14885/com.boiledcoffee.welfare W/System.err:     at com.boiledcoffee.welfare.repository.ImageRepository.lambda$getAtlas$1$ImageRepository(ImageRepository.java:141)
05-16 10:58:20.000 14885-14885/com.boiledcoffee.welfare W/System.err:     at com.boiledcoffee.welfare.repository.ImageRepository$$Lambda$3.apply(Unknown Source)
05-16 10:58:20.000 14885-14885/com.boiledcoffee.welfare W/System.err:     at io.reactivex.internal.operators.observable.ObservableMap$MapObserver.onNext(ObservableMap.java:59)
05-16 10:58:20.000 14885-14885/com.boiledcoffee.welfare W/System.err:     at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.drainNormal(ObservableObserveOn.java:200)
05-16 10:58:20.000 14885-14885/com.boiledcoffee.welfare W/System.err:     at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.run(ObservableObserveOn.java:252)
05-16 10:58:20.000 14885-14885/com.boiledcoffee.welfare W/System.err:     at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:109)
05-16 10:58:20.000 14885-14885/com.boiledcoffee.welfare W/System.err:     at android.os.Handler.handleCallback(Handler.java:742)
05-16 10:58:20.000 14885-14885/com.boiledcoffee.welfare W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:95)
05-16 10:58:20.000 14885-14885/com.boiledcoffee.welfare W/System.err:     at android.os.Looper.loop(Looper.java:157)
05-16 10:58:20.000 14885-14885/com.boiledcoffee.welfare W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5653)
05-16 10:58:20.000 14885-14885/com.boiledcoffee.welfare W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
05-16 10:58:20.000 14885-14885/com.boiledcoffee.welfare W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:746)
05-16 10:58:20.000 14885-14885/com.boiledcoffee.welfare W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:636)
05-16 10:58:20.018 14885-14885/com.boiledcoffee.welfare W/System.err: java.lang.NumberFormatException: Invalid int: "下一页»"
05-16 10:58:20.018 14885-14885/com.boiledcoffee.welfare W/System.err:     at java.lang.Integer.invalidInt(Integer.java:138)
05-16 10:58:20.018 14885-14885/com.boiledcoffee.welfare W/System.err:     at java.lang.Integer.parse(Integer.java:410)
05-16 10:58:20.018 14885-14885/com.boiledcoffee.welfare W/System.err:     at java.lang.Integer.parseInt(Integer.java:367)
05-16 10:58:20.018 14885-14885/com.boiledcoffee.welfare W/System.err:     at java.lang.Integer.parseInt(Integer.java:334)
05-16 10:58:20.018 14885-14885/com.boiledcoffee.welfare W/System.err:     at com.boiledcoffee.welfare.repository.ImageRepository.hasPage(ImageRepository.java:212)
05-16 10:58:20.018 14885-14885/com.boiledcoffee.welfare W/System.err:     at com.boiledcoffee.welfare.repository.ImageRepository.parseAtlasData(ImageRepository.java:168)
05-16 10:58:20.019 14885-14885/com.boiledcoffee.welfare W/System.err:     at com.boiledcoffee.welfare.repository.ImageRepository.lambda$getAtlas$1$ImageRepository(ImageRepository.java:141)
05-16 10:58:20.019 14885-14885/com.boiledcoffee.welfare W/System.err:     at com.boiledcoffee.welfare.repository.ImageRepository$$Lambda$3.apply(Unknown Source)
05-16 10:58:20.019 14885-14885/com.boiledcoffee.welfare W/System.err:     at io.reactivex.internal.operators.observable.ObservableMap$MapObserver.onNext(ObservableMap.java:59)
05-16 10:58:20.019 14885-14885/com.boiledcoffee.welfare W/System.err:     at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.drainNormal(ObservableObserveOn.java:200)
05-16 10:58:20.019 14885-14885/com.boiledcoffee.welfare W/System.err:     at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.run(ObservableObserveOn.java:252)
05-16 10:58:20.019 14885-14885/com.boiledcoffee.welfare W/System.err:     at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:109)
05-16 10:58:20.019 14885-14885/com.boiledcoffee.welfare W/System.err:     at android.os.Handler.handleCallback(Handler.java:742)
05-16 10:58:20.019 14885-14885/com.boiledcoffee.welfare W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:95)
05-16 10:58:20.019 14885-14885/com.boiledcoffee.welfare W/System.err:     at android.os.Looper.loop(Looper.java:157)
05-16 10:58:20.019 14885-14885/com.boiledcoffee.welfare W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5653)
05-16 10:58:20.019 14885-14885/com.boiledcoffee.welfare W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
05-16 10:58:20.019 14885-14885/com.boiledcoffee.welfare W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:746)
05-16 10:58:20.019 14885-14885/com.boiledcoffee.welfare W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:636)
05-16 10:58:20.023 14885-14885/com.boiledcoffee.welfare W/System.err: java.lang.NumberFormatException: Invalid int: "下一页»"

**Comment by boildcoffee** [comment]
好的。找个时间我改改。感谢提醒

**Comment by tianshaokai** [comment]
![image](https://user-images.githubusercontent.com/6706496/40298964-6292f0f2-5d17-11e8-9a84-6b022ff454cf.png)
没有修复成功

**Comment by tianshaokai** [comment]
作者 爬过其他网站内容吗，比如js动态创建的

**Comment by tianshaokai** [comment]
![image](https://user-images.githubusercontent.com/6706496/40299148-e9b573e8-5d17-11e8-93b4-065534eb5d14.png)
还有一个关于数据库的问题
